### ISSUE TITLE
在手动起一个爬虫的时候，启动成功了，但是列表的运行中的数值不对

### ISSUE THREAD

**Issue by MrJo621** [nekolr/slime#23]
![image](https://user-images.githubusercontent.com/65753320/162677208-2943181e-b431-4e99-8a39-3a1ac6952642.png)

还是0，实际是在运行在的1
而且查看任务详情的时候，点停止，停止失败

**Comment by nekolr** [comment]
> ![image](https://user-images.githubusercontent.com/65753320/162677208-2943181e-b431-4e99-8a39-3a1ac6952642.png)
> 
> 还是0，实际是在运行在的1 而且查看任务详情的时候，点停止，停止失败

手动执行，运行正常，只是不更新运行中个数，同时不能手动停止是么。

**Comment by nekolr** [comment]
> ![image](https://user-images.githubusercontent.com/65753320/162677208-2943181e-b431-4e99-8a39-3a1ac6952642.png)
> 
> 还是0，实际是在运行在的1 而且查看任务详情的时候，点停止，停止失败

已修复
