### ISSUE TITLE
docker运行时候，如何做数据的持久化保存？

### ISSUE THREAD

**Issue by star7th** [nekolr/slime#24]
我是使用这个镜像运行的 nekolr/slime:latest 

文档里说是采用内置数据库H2 ，那么如何做持久化呢，不然服务重启后我的配置爬虫不见了

**Comment by nekolr** [comment]
> 我是使用这个镜像运行的 nekolr/slime:latest
> 
> 文档里说是采用内置数据库H2 ，那么如何做持久化呢，不然服务重启后我的配置爬虫不见了

`/root/slime` 目录中包含项目生成的所有文件，在使用 docker run 命令时可以像这样来指定持久化目录：`-v 你宿主机的目录:/root/slime`
