### ISSUE TITLE
docker容器无法新建全局变量

### ISSUE THREAD

**Issue by star7th** [nekolr/slime#26]
使用的镜像是nekolr/slime:latest

在左侧菜单“全局变量”，添加变量，点击保存时候提示请求失败.

看了下网络请求，接口/variable/save 返回500错误，提示 {"message":null,"timestamp":"2022-05-11 18:48:23"}

**Comment by nekolr** [comment]
> 使用的镜像是nekolr/slime:latest
> 
> 在左侧菜单“全局变量”，添加变量，点击保存时候提示请求失败.
> 
> 看了下网络请求，接口/variable/save 返回500错误，提示 {"message":null,"timestamp":"2022-05-11 18:48:23"}

已修复，感谢反馈！

**Comment by star7th** [comment]
你已经只是修复代码而没有更新docker镜像吧。我看到的构建还是一个月前的 https://hub.docker.com/r/nekolr/slime/tags

你可以写个github action脚本，每次有更新的时候自动构建并推送到docker hub 。可网络搜索下怎么写，或者参考下我的开源项目 https://github.com/star7th/showdoc/blob/master/.github/workflows/docker.yml

**Comment by nekolr** [comment]
> 你已经只是修复代码而没有更新docker镜像吧。我看到的构建还是一个月前的 https://hub.docker.com/r/nekolr/slime/tags
> 
> 你可以写个github action脚本，每次有更新的时候自动构建并推送到docker hub 。可网络搜索下怎么写，或者参考下我的开源项目 https://github.com/star7th/showdoc/blob/master/.github/workflows/docker.yml

感谢建议，其实有这个计划来着，我会参考的！

**Comment by nekolr** [comment]
> 你应该只是修复代码而没有更新docker镜像。我看到的构建还是一个月前的 https://hub.docker.com/r/nekolr/slime/tags
> 
> 你可以写个github action脚本，每次有更新的时候自动构建并推送到docker hub 。可网络搜索下怎么写，或者参考下我的开源项目 https://github.com/star7th/showdoc/blob/master/.github/workflows/docker.yml

docker 镜像已更新。
