### ISSUE TITLE
如何在执行sql前加判断,判断变量是否为空？

### ISSUE THREAD

**Issue by fendo8888** [nekolr/slime#32]
如何在执行sql前加判断,判断变量是否为空？如果变量全部为空的话

![image](https://user-images.githubusercontent.com/22114481/193707787-6ee4069f-2480-4fde-a93d-ab01f46cc774.png)

则后面的sql就不执行，避免插入空数据到数据库

**Comment by nekolr** [comment]
> 如何在执行sql前加判断,判断变量是否为空？如果变量全部为空的话
> 
> ![image](https://user-images.githubusercontent.com/22114481/193707787-6ee4069f-2480-4fde-a93d-ab01f46cc774.png)
> 
> 则后面的sql就不执行，避免插入空数据到数据库

可以设置流转条件，点击直线箭头可以看到。

**Comment by fendo8888** [comment]
已搞定，谢谢
