### ISSUE TITLE
代理管理这块怎么用的啊？没看到相关的demo

### ISSUE THREAD

**Issue by fendo8888** [nekolr/slime#36]
代理管理这块怎么用的啊？没看到相关的demo

**Comment by nekolr** [comment]
> 代理管理这块怎么用的啊？没看到相关的demo

一般的代理服务都提供了 http 接口，获取到的数据通过内置函数添加到系统的代理池中即可，具体函数可以参考：

https://www.spiderflow.org/plugins/proxypool.html#%E5%BC%95%E5%85%A5ip%E4%BB%A3%E7%90%86%E6%B1%A0%E6%8F%92%E4%BB%B6
