### ISSUE TITLE
自定义函数中如何操作selenium有demo么？

### ISSUE THREAD

**Issue by fendo8888** [nekolr/slime#37]
自定义函数中如何操作selenium有demo么？

**Comment by nekolr** [comment]
> 自定义函数中如何操作selenium有demo么？

参考这个：https://www.spiderflow.org/plugins/selenium.html#%E5%BC%95%E5%85%A5selenium%E6%8F%92%E4%BB%B6

**Comment by fendo8888** [comment]
自定义函数！！

**Comment by fendo8888** [comment]
![image](https://user-images.githubusercontent.com/22114481/197966894-ff7f39f2-a356-4306-b65f-e013cd9b7d11.png)

**Comment by nekolr** [comment]
> ![image](https://user-images.githubusercontent.com/22114481/197966894-ff7f39f2-a356-4306-b65f-e013cd9b7d11.png)

这里不能操作 selenium

**Comment by fendo8888** [comment]
有啥好的方式能操作？
![image](https://user-images.githubusercontent.com/22114481/197969422-29ab9036-acb5-485e-846d-5de08935994d.png)
写个插件？我主要是想简单的操作selenium过下百度的这个旋转验证码

**Comment by nekolr** [comment]
> 

理论上这个方法能够模拟鼠标拖动，但是如何计算拖动的位置可能比较麻烦

**Comment by fendo8888** [comment]
> > 
> 
> 理论上这个方法能够模拟鼠标拖动，但是如何计算拖动的位置可能比较麻烦

是的，如果能在自定义函数中通过js的方式操作要简单些。我写个JAVA方法，去操作算了
