### ISSUE TITLE
添加屏蔽所有selenium指纹和特征的功能

### ISSUE THREAD

**Issue by fendo8888** [nekolr/slime#38]
参考：https://blog.csdn.net/fx9590/article/details/112744326

**Comment by nekolr** [comment]
> 参考：https://blog.csdn.net/fx9590/article/details/112744326

感谢提供的参考。目前我在本地测试，使用该方案控制的浏览器打开 <https://bot.sannysoft.com/> 页面，基本上能够隐藏特征，`stealth.min.js` 文件可以通过 `https://github.com/berstend/puppeteer-extra/tree/master/packages/extract-stealth-evasions` 来定期生成。

**Comment by nekolr** [comment]
closed #39
