### ISSUE TITLE
全局变量如何修改？

### ISSUE THREAD

**Issue by fendo8888** [nekolr/slime#41]
全局变量如何在爬虫里修改？
通过定时任务每分钟执行一次，从全局变量里取值，执行完后加一，下次定时任务取修改后的值？这个要怎么操作

**Comment by nekolr** [comment]
> 全局变量如何在爬虫里修改？ 通过定时任务每分钟执行一次，从全局变量里取值，执行完后加一，下次定时任务取修改后的值？这个要怎么操作

目前没有提供比较方便的修改入口，可以通过修改 `ExpressionGlobalVariables` 类，然后编写扩展函数来支持，欢迎 PR。

**Comment by fendo8888** [comment]
> > 全局变量如何在爬虫里修改？ 通过定时任务每分钟执行一次，从全局变量里取值，执行完后加一，下次定时任务取修改后的值？这个要怎么操作
> 
> 目前没有提供比较方便的修改入口，可以通过修改 `ExpressionGlobalVariables` 类，然后编写扩展函数来支持，欢迎 PR。

代码里去操作，同步到数据库，说不定会锁，暂时用SQL操作解决了

**Comment by nekolr** [comment]
closed b3664ed6f6d750310b206d2838726e925d1e89be
