### ISSUE TITLE
我想请教下，执行函数节点的表达式内部如何使用其他变量？

### ISSUE THREAD

**Issue by kangerts** [nekolr/slime#45]
${resp.xpath("//*[@id='LAY-user-login-username']").sendKeys(${username})}
我想请教下，执行函数节点的表达式内部如何使用其他变量？
类似上面这个表达式，请大佬指教

**Comment by nekolr** [comment]
> Unable to render expression. ${resp.xpath("//*[{username})} 我想请教下，执行函数节点的表达式内部如何使用其他变量？ 类似上面这个表达式，请大佬指教

直接用，因为你最外边已经用 ${} 包裹了

**Comment by kangerts** [comment]
> > Unable to render expression. ${resp.xpath("//*[{username})} 我想请教下，执行函数节点的表达式内部如何使用其他变量？ 类似上面这个表达式，请大佬指教
> 
> 直接用，因为你最外边已经用 ${} 包裹了

好的，谢谢
